version = 0.1
[default.deploy.parameters]
stack_name = "tfc-12-cli"
resolve_s3 = true
s3_prefix = "tfc-12-cli"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
